"""Pull request title and body: request, design doc, tasks, test results and the Q&A log."""

from __future__ import annotations

from collections.abc import Mapping
from typing import Any

MAX_BODY = 60_000  # GitHub's limit is 65,536 characters
MAX_DESIGN = 25_000
MAX_LOG = 3_000


def _cell(text: object) -> str:
    return str(text).replace("|", "\\|").replace("\n", " ").strip()


def _clip(text: str, limit: int) -> str:
    return text if len(text) <= limit else text[:limit] + "\n\n… (truncated)"


def pr_title(request: str) -> str:
    first = request.strip().splitlines()[0] if request.strip() else "DevCrew run"
    return f"DevCrew: {first[:72]}{'…' if len(first) > 72 else ''}"


def pr_body(state: Mapping[str, Any]) -> str:
    plan = state.get("plan") or {}
    design = state.get("design") or {}
    tasks: Mapping[str, Mapping[str, Any]] = state.get("tasks") or {}
    titles = {t["id"]: t for t in plan.get("tasks", [])}
    integration = state.get("integration") or {}
    parts: list[str] = []

    parts.append(f"## Request\n\n{state.get('request', '').strip()}")
    if plan.get("summary"):
        parts.append(f"## Summary\n\n{plan['summary']}")
        stories = plan.get("user_stories") or []
        if stories:
            lines = []
            for s in stories:
                lines.append(f"- **{s['id']}** {s['story']}")
                lines += [f"  - {ac}" for ac in s.get("acceptance_criteria", [])]
            parts.append("### User stories\n\n" + "\n".join(lines))

    if design:
        stack = design.get("stack", "")
        template = design.get("template_id", "")
        doc = _clip(design.get("design_doc", ""), MAX_DESIGN)
        parts.append(
            f"## Design\n\nStack `{stack}`, template `{template}`.\n\n"
            f"<details><summary>Design document</summary>\n\n{doc}\n\n</details>"
        )

    rows = ["| Task | Title | Stack | Status | Attempts | Tests |", "|---|---|---|---|---|---|"]
    for tid, t in tasks.items():
        info = titles.get(tid, {})
        task_tests = t.get("test_results") or {}
        result = (
            "not run"
            if not task_tests.get("ran")
            else ("passed" if task_tests.get("passed") else "failed")
        )
        rows.append(
            f"| {tid} | {_cell(info.get('title', ''))} | {info.get('stack', '')} | "
            f"{t.get('status', '')} | {t.get('iterations', 0)} | {result} |"
        )
    parts.append("## Tasks\n\n" + "\n".join(rows))

    tests: Mapping[str, Mapping[str, Any]] = integration.get("tests") or {}
    if tests:
        lines = ["| Stack | Result | Command |", "|---|---|---|"]
        details = []
        for stack, r in tests.items():
            result = (
                "not run" if not r.get("ran") else ("✅ passed" if r.get("passed") else "❌ failed")
            )
            lines.append(f"| {stack} | {result} | `{r.get('command') or ''}` |")
            if r.get("ran") and not r.get("passed"):
                log = _clip(r.get("logs_excerpt", ""), MAX_LOG)
                details.append(
                    f"<details><summary>{stack} test output</summary>\n\n"
                    f"```\n{log}\n```\n\n</details>"
                )
        parts.append(
            "## Test results (integration branch)\n\n"
            + "\n".join(lines)
            + ("\n\n" + "\n\n".join(details) if details else "")
        )

    qa = state.get("qa_log") or []
    if qa:
        lines = []
        for e in qa:
            scope = f" ({e['task_id']})" if e.get("task_id") else ""
            lines.append(
                f"- **{e['asker']} → {e['target']}**{scope}: {e['question']}\n  - {e['answer']}"
            )
        parts.append("## Q&A log\n\n" + "\n".join(lines))

    parts.append(f"---\n_Generated by DevCrew (run `{state.get('run_id', '')}`)._")
    return _clip("\n\n".join(parts), MAX_BODY)
