"""Run report (Phase 16): one Markdown file with the whole run, for sharing or archiving."""

from __future__ import annotations

from collections.abc import Mapping, Sequence
from datetime import datetime
from typing import Any

from app.github.pr_body import pr_body
from app.services.usage import RunUsage
from app.services.workflow import Workflow

MAX_REQUEST_IN_REPORT = 60_000


def _cell(text: object) -> str:
    return str(text if text is not None else "").replace("|", "\\|").replace("\n", " ").strip()


def _when(at: datetime | None) -> str:
    return at.strftime("%Y-%m-%d %H:%M:%S") if at else ""


def _duration(seconds: float) -> str:
    seconds = int(seconds)
    if seconds < 60:
        return f"{seconds}s"
    minutes, s = divmod(seconds, 60)
    if minutes < 60:
        return f"{minutes}m {s:02d}s"
    hours, m = divmod(minutes, 60)
    return f"{hours}h {m:02d}m"


def run_report(
    *,
    run: Any,
    state: Mapping[str, Any],
    workflow: Workflow,
    usage: RunUsage,
    messages: Sequence[Any],
) -> str:
    parts = [f"# DevCrew run `{run.id}`"]
    facts = [
        ("Status", run.status),
        ("Repository", f"`{run.repo_target}`"),
        ("Started", _when(run.created_at)),
        ("Last update", _when(run.updated_at)),
        ("Pull request", run.pr_url or "none"),
    ]
    if state.get("target") == "existing":
        facts.append(("Target", f"existing repository, {state.get('mode', 'full')} mode"))
    models = state.get("models") or {}
    if models:
        facts.append(("Models", ", ".join(f"{r}: `{m}`" for r, m in sorted(models.items()))))
    if run.error:
        facts.append(("Error", _cell(run.error)[:500]))
    parts.append("\n".join(f"- **{k}:** {v}" for k, v in facts))

    lines = ["| Stage | Status | Started | Finished | Runs | Detail |", "|---|---|---|---|---|---|"]
    for n in workflow.nodes:
        lines.append(
            f"| {_cell(n.label)} | {n.status} | {_when(n.started_at)} | {_when(n.finished_at)} | "
            f"{n.runs} | {_cell(n.detail)} |"
        )
    parts.append("## Timeline\n\n" + "\n".join(lines))

    lines = [
        f"- **Tokens:** {usage.total_tokens:,} ({usage.input_tokens:,} in, "
        f"{usage.output_tokens:,} out) in {usage.calls} model calls",
        f"- **Model time:** {_duration(usage.model_seconds)}",
        f"- **Working time:** {_duration(usage.active_s)} "
        f"(waiting for you: {_duration(usage.waiting_s)})",
    ]
    if usage.by_role:
        lines += ["", "| Role | Models | Calls | Tokens | Model time |", "|---|---|---|---|---|"]
        for line in usage.by_role:
            lines.append(
                f"| {line.key} | {_cell(', '.join(line.models))} | {line.calls} | "
                f"{line.total_tokens:,} | {_duration(line.model_seconds)} |"
            )
    parts.append("## Usage\n\n" + "\n".join(lines))

    body = pr_body({**state, "request": str(state.get("request", ""))[:MAX_REQUEST_IN_REPORT]})
    body = body.rsplit("\n\n---\n_Generated by DevCrew", 1)[0]
    parts.append(body)

    if messages:
        lines = []
        for m in messages:
            to = f" → {m.task_id}" if m.task_id else ""
            lines.append(f"- **You{to}** ({_when(m.created_at)}, {m.status}): {m.text}")
            if m.reply:
                lines.append(f"  - **DevCrew:** {m.reply}")
        parts.append("## Messages to the crew\n\n" + "\n".join(lines))

    errors = state.get("errors") or []
    if errors:
        parts.append("## Errors\n\n" + "\n".join(f"- {_cell(e)[:1000]}" for e in errors))
    parts.append(f"---\n_Report generated by DevCrew for run `{run.id}`._")
    return "\n\n".join(parts) + "\n"
