"""Run report (Markdown export) and the code-search status (Phase 16)."""

from __future__ import annotations

from pathlib import Path
from typing import Any

from app.config import Settings
from app.events.types import Event, EventType
from app.rag.service import RagService
from app.services.code_search import code_search_status
from tests.api_harness import api
from tests.fakes import FakeChroma

REQUEST = {"request": "Build a TODO API with CRUD", "repo_target": "me/todo", "create_repo": False}


async def test_report_has_the_whole_run(tmp_path: Path) -> None:
    async with api(tmp_path) as a:
        run_id = (await a.client.post("/runs", json=REQUEST)).json()["id"]
        await a.settle(run_id)
        resp = await a.client.post(f"/runs/{run_id}/messages", json={"text": "use UUIDs"})
        assert resp.status_code == 201
        await a.approve(run_id)
        await a.approve(run_id)
        await a.approve(run_id)
        resp = await a.client.get(f"/runs/{run_id}/report.md")
        assert resp.status_code == 200
        assert resp.headers["content-type"].startswith("text/markdown")
        assert f'filename="devcrew-run-{run_id}.md"' in resp.headers["content-disposition"]
        text = resp.text
        assert text.startswith(f"# DevCrew run `{run_id}`")
        assert "- **Status:** completed" in text and "`me/todo`" in text
        for section in ("## Timeline", "## Usage", "## Request", "## Tasks", "## Messages"):
            assert section in text, section
        assert "| T1 · Todo model | done |" in text
        assert "Build a TODO API with CRUD" in text and "use UUIDs" in text
        assert "| planner | fake |" in text  # tokens per role, with the model
        assert "Generated by DevCrew (run" not in text  # the PR footer is replaced
        assert (await a.client.get("/runs/nope/report.md")).status_code == 404


async def test_code_search_status_follows_indexing(tmp_path: Path) -> None:
    async with api(tmp_path, chroma=FakeChroma()) as a:
        run_id = (await a.client.post("/runs", json=REQUEST)).json()["id"]
        run = await a.settle(run_id)
        assert run["code_search"]["status"] in ("pending", "ok")
        rag = a.harness.deps.rag
        assert rag is not None

        async def broken(run_id: str, root: Path) -> Any:
            raise ConnectionError("chroma is down")

        rag._sync_workspace = broken  # type: ignore[method-assign]
        await a.approve(run_id)
        run = await a.approve(run_id)
        status = run["code_search"]
        assert status["status"] == "unavailable" and "chroma is down" in status["detail"]


async def test_code_search_disabled_without_rag(tmp_path: Path) -> None:
    async with api(tmp_path) as a:
        run_id = (await a.client.post("/runs", json=REQUEST)).json()["id"]
        run = await a.settle(run_id)
        assert run["code_search"]["status"] == "disabled"


def test_code_search_status_after_a_restart_reads_the_event_log(tmp_path: Path) -> None:
    rag = RagService(FakeChroma, None, Settings(_env_file=None))  # type: ignore[arg-type]

    def event(i: int, type: EventType, **payload: Any) -> Event:
        return Event(id=i, run_id="r", type=type, payload=payload)

    ok = event(1, EventType.TOOL_RESULT, tool="index_codebase", ok=True)
    failed = event(2, EventType.ERROR, message="indexing failed: timeout")
    assert code_search_status(rag, "r", []).status == "pending"
    assert code_search_status(rag, "r", [ok]).status == "ok"
    status = code_search_status(rag, "r", [ok, failed])
    assert status.status == "unavailable" and status.detail == "indexing failed: timeout"
    assert code_search_status(rag, "r", [failed, ok]).status == "ok"
